export const AVENGERS_LOADING ="AVENGERS_LOADING";
export const AVENGERS_SUCCESS = "AVENGERS_SUCCESS";
export const AVENGERS_FAILED = "AVENGERS_FAILED";
export const AVENGERS_CLEAR = "AVENGERS_CLEAR";
export const IMAGES_LOADING = "IMAGES_LOADING";
export const IMAGES_SUCCESS = "IMAGES_SUCCESS";
export const IMAGES_FAILED = "IMAGES_FAILED";
export const IMAGES_CLEAR = "IMAGES_CLEAR";